- hosts: localhost
  connection: local
  gather_facts: no           
  sudo: no
  vars:
    homebrew_taps:
      - caskroom/cask
      - homebrew/dupes/
      - homebrew/x11/
      - snmsts/roswell/
    homebrew_packages:
      - { name: ghc }
      - { name: cabal-install }
      - { name: ocaml }
      - { name: imagemagick }
      - { name: cask }
      - { name: cmake }
      - { name: readline }
      - { name: openssl }
      - { name: python }
      - { name: llvm }
      - { name: clang-format }
      - { name: nkf }
      - { name: cmigemo }
      - { name: coq }
      - { name: gauche }
      - { name: gnu-sed }
      - { name: leiningen }
      - { name: lftp }
      - { name: pandoc }
      - { name: proof-general }
      - { name: racket }
      - { name: rlwrap }
      - { name: ruby }
      - { name: stow }
      - { name: wget}
      - { name: screen }
      - { name: swi-prolog }
      - { name: roswell }
    homebrew_cask_packages:
      - { name: emacs-mac }
      - { name: iterm2 }
      - { name: google-chrome }
      - { name: java }
      - { name: skype }
      - { name: slack }
      - { name: karabiner }
      - { name: vagrant }
      - { name: virtualbox }
      - { name: aquaterm }
      - { name: amethyst }
      - { name: mactex }

  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: homebrew_taps

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: homebrew_packages
      register: brew_result
    - name: brew パッケージの情報保存先ディレクトリを作成
      file: path=brew_info state=directory
    - name: brew パッケージの情報を保存
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list

    # cask
    - name: homebrew-cask のインストール
      homebrew: name=brew-cask state=latest
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: homebrew_cask_packages
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    - name: cask パッケージの情報を保存
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list
